./configure \
--cc=clang \
--as='/Applications/Xcode.app/Contents/Developer/usr/bin/gcc' \
--sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk \
--target-os=darwin \
--arch=x86_64 \
--cpu=x86_64 \
--extra-cflags='-arch x86_64 -I/usr/local/include' \
--extra-ldflags='-arch x86_64 -L/usr/local/lib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk' \
--prefix=/Users/biezhihua/StudySpace/FFmpegBuildTool/macos/tools/build \
--enable-cross-compile \
--disable-swscale-alpha \
--disable-doc \
--disable-ffmpeg \
--disable-ffplay \
--disable-ffprobe \
--disable-asm \
--disable-debug \
--enable-libmp3lame