/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n4.1.1-3-g53f3f5233f3"
#endif /* AVUTIL_FFVERSION_H */
